import { convertFileSrc } from "@tauri-apps/api/core";
import { useEffect, useRef, useState } from "react";
import { TrackProgress, TransportControls, useNowPlaying } from "../components/NowPlaying";
import { ipc } from "../lib/ipc";
import type { LocalTrack } from "../lib/types";

export function MediaPage() {
  const external=useNowPlaying(true); const [tab,setTab]=useState<"library"|"players">("library"); const [tracks,setTracks]=useState<LocalTrack[]>([]); const [index,setIndex]=useState(-1); const [playing,setPlaying]=useState(false); const [query,setQuery]=useState(""); const audio=useRef<HTMLAudioElement>(null);
  useEffect(()=>{void ipc.musicLibrary().then(setTracks).catch(()=>setTracks([]));},[]);
  const current=tracks[index]; const visible=tracks.filter(track=>`${track.title} ${track.artist} ${track.album}`.toLowerCase().includes(query.toLowerCase()));
  const play=async(next:number)=>{if(next<0||next>=tracks.length)return;setIndex(next);setPlaying(true);window.setTimeout(()=>void audio.current?.play().catch(()=>setPlaying(false)),0);};
  const toggle=()=>{if(!audio.current)return;if(audio.current.paused){void audio.current.play();setPlaying(true);}else{audio.current.pause();setPlaying(false);}};
  useEffect(()=>{if(!current||!("mediaSession" in navigator))return;navigator.mediaSession.metadata=new MediaMetadata({title:current.title,artist:current.artist,album:current.album,artwork:current.artPath?[{src:convertFileSrc(current.artPath)}]:[]});navigator.mediaSession.setActionHandler("play",toggle);navigator.mediaSession.setActionHandler("pause",toggle);navigator.mediaSession.setActionHandler("nexttrack",()=>void play((index+1)%tracks.length));navigator.mediaSession.setActionHandler("previoustrack",()=>void play((index-1+tracks.length)%tracks.length));},[current,index,tracks.length]);
  return <div className="music-page"><div className="page-head edith-head"><div><h1>Music</h1><div className="page-sub">Your local library and every Linux player</div></div></div><div className="pill-tabs"><button className={tab==="library"?"active":""} onClick={()=>setTab("library")}>Library</button><button className={tab==="players"?"active":""} onClick={()=>setTab("players")}>Other players</button></div>
    {tab==="library"&&<><section className="music-player local-player"><div className="music-art">{current?.artPath?<img src={convertFileSrc(current.artPath)} alt=""/>:<span>♪</span>}</div><div className="music-copy"><span className="music-source">LOCAL LIBRARY</span><h2>{current?.title||"Choose a track"}</h2><p>{current?`${current.artist} · ${current.album}`:"Audio files under ~/Music appear below."}</p>{current&&<audio ref={audio} src={convertFileSrc(current.path)} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>void play((index+1)%tracks.length)} controls/>}<div className="music-controls"><button className="transport" disabled={!current} onClick={()=>void play((index-1+tracks.length)%tracks.length)}>‹</button><button className="transport primary" disabled={!current} onClick={toggle}>{playing?"Ⅱ":"▶"}</button><button className="transport" disabled={!current} onClick={()=>void play((index+1)%tracks.length)}>›</button></div></div></section><section className="card"><div className="card-head"><h2>Tracks</h2><input className="search" placeholder="Search library" value={query} onChange={e=>setQuery(e.target.value)}/></div>{visible.length?<div className="list music-library">{visible.map(track=>{const realIndex=tracks.findIndex(item=>item.id===track.id);return <button className={`list-row ${realIndex===index?"active":""}`} key={track.id} onClick={()=>void play(realIndex)}><div><strong>{track.title}</strong><small>{track.artist} · {track.album}</small></div><span>{realIndex===index&&playing?"Playing":"Play"}</span></button>;})}</div>:<div className="empty"><h3>No local tracks</h3><p>Put MP3, FLAC, OGG, Opus, WAV, M4A, AAC or WebM files under ~/Music, then reopen this page.</p></div>}</section></>}
    {tab==="players"&&<>{external.unavailable?<div className="empty"><h3>No desktop media session</h3></div>:!external.playing?<div className="empty"><h3>No player is active</h3><p>Start Spotify, Rhythmbox, VLC or media in a browser.</p></div>:<section className="music-player blur-music"><div className="music-art">{external.playing.artUrl?<img src={external.playing.artUrl} alt=""/>:<span>♪</span>}</div><div className="music-copy"><span className="music-source">{external.playing.identity}</span><h2>{external.playing.title}</h2><p>{external.playing.artist}</p><TrackProgress playing={external.playing}/><TransportControls playing={external.playing} control={external.control}/></div></section>}</>}
  </div>;
}
