[package]
name = "veronica-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "vr"
path = "src/main.rs"

[dependencies]
veronica-core = { workspace = true }
veronica-usage = { workspace = true }
veronica-system = { workspace = true }
veronica-media = { workspace = true }
veronica-calendar = { workspace = true }
veronica-machines = { workspace = true }
zbus = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
